[package]
name = "custom-libc"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlite-wasm-rs = { path = "../..", features = ["custom-libc"] }

js-sys = "0.3.77"
wasm-bindgen = "0.2.100"
wasm-bindgen-test = "0.3.50"
web-sys = { version = "0.3.77", features = [
  "Performance",
  "Window",
]}
