on:
  workflow_dispatch:

jobs:
  precompile:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup emscripten
      uses: ./.github/actions/setup-emscripten
    - name: Build
      run: |
        rustup toolchain install 1.78.0
        rustup default 1.78.0
        rustup target add wasm32-unknown-unknown
        export CARGO_PROFILE_RELEASE_OPT_LEVEL="z"
        SQLITE_WASM_RS_UPDATE_PREBUILD=1 cargo build --target wasm32-unknown-unknown --features bundled,buildtime-bindgen --release
        SQLITE_WASM_RS_UPDATE_PREBUILD=1 cargo build --target wasm32-unknown-unknown --features sqlite3mc,buildtime-bindgen --release
        rm -rf ../emsdk

    - name: Set commit message
      id: commit_message_step
      run: |
        WORKFLOW_URL="https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        echo 'commit_message<<EOF' >> $GITHUB_OUTPUT
        echo 'Update precompiled library and bindings' >> $GITHUB_OUTPUT
        echo $WORKFLOW_URL >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ${{ steps.commit_message_step.outputs.commit_message }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-path: |
          sqlite-wasm-rs/sqlite3/libsqlite3.a
