name: isar_community_generator
description: Code generator for the Isar Database. Finds classes annotated with @Collection.
version: 3.3.0-dev.2
repository: https://github.com/isar-community/isar-community
homepage: https://github.com/isar-community/isar-community
issue_tracker: https://github.com/isar-community/isar-community/issues
documentation: https://isar-community.dev
funding:
  - https://github.com/sponsors/vicenterusso/

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  analyzer: ">=7.4.5 <9.0.0"
  build: ^3.0.0
  dart_style: ^3.0.1
  dartx: ^1.1.0
  glob: ^2.0.2
  isar_plus: 3.3.0-dev.2
  path: ^1.8.1
  source_gen: ^3.0.0
  xxh3: ^1.0.1

dev_dependencies:
  build_test: ^3.3.2
  logging: 1.3.0
  matcher: ^0.12.12
  test: ^1.21.0
  very_good_analysis: ^7.0.0

dependency_overrides:
  isar_plus:
    path: ../isar_plus
